name: Publish to GitHub Packages

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Create artifacts directory
      run: mkdir -p ./artifacts

    - name: Pack Abstractions
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        cd src/UniDAL.SQL.Abstractions
        dotnet pack \
          --configuration Release \
          -p:PackageVersion=$VERSION \
          -p:Version=$VERSION \
          --output ../../artifacts

    - name: Pack Core
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        cd src/UniDAL.SQL.Core
        dotnet pack \
          --configuration Release \
          -p:PackageVersion=$VERSION \
          -p:Version=$VERSION \
          --output ../../artifacts

    - name: List artifacts (debug)
      run: ls -la ./artifacts

    - name: Publish to GitHub Packages
      run: |
        dotnet nuget push ./artifacts/*.nupkg \
          --skip-duplicate \
          --api-key ${{ secrets.GITHUB_TOKEN }} \
          --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json